_wandb:
    value:
        cli_version: 0.24.2
        e:
            dsnf4lh4gkvdanpab67hmuzg4ot4l2k8:
                cpu_count: 12
                cpu_count_logical: 20
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "501809635328"
                        used: "278930665472"
                email: minje227@hanyang.ac.kr
                executable: /home/minje/miniconda3/envs/icpbl/bin/python
                git:
                    commit: a0f66f3d5c8c2c551472e346e726ed3027f6f391
                    remote: https://github.com/minje227-coder/icpbl-wafer-open-set.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-1d04c897-f06f-0f59-aedb-d9a1172cbb90
                host: minje-24.04
                memory:
                    total: "33379586048"
                os: Linux-6.17.0-22-generic-x86_64-with-glibc2.39
                program: <stdin>
                python: CPython 3.13.11
                root: /home/minje/icpbl-wafer-open-set
                startedAt: "2026-06-04T04:17:55.638580Z"
                writerId: dsnf4lh4gkvdanpab67hmuzg4ot4l2k8
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.11
            "5": 0.24.2
            "12": 0.24.2
            "13": linux-x86_64
augmentation:
    value:
        autocontrast_p: 0.17
        contrast_strength: 0.08
        rotation_degrees: 5
        sharpness_factor: 1.1
        sharpness_p: 0.2
batch_size:
    value: 8
epochs:
    value: 30
experiment:
    value: fs_r3_ac17_sharp110_p20
image_size:
    value: 224
label_smoothing:
    value: 0.05
learning_rate:
    value: 0.0001
weight_decay:
    value: 0.0001
